name: VConomy
main: org.vaelow233.vconomy.bukkit.VConomyBukkitPlugin
version: 0.0.2
api-version: 1.13
author: Vaelow233
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  vconomy:
    description: VConomy economy manager command
  balancetop:
    description: VConomy balance top command
  balance:
    description: VConomy show balance command
  pay:
    description: VConomy pay command
permissions:
  vconomy.get:
    description: Allows you to get the balance of yourself
    default: true
  vconomy.top:
    description: Allows you to see the balance top
    default: true
  vconomy.pay:
    description: Allows you to pay money to someone
    default: true
  vconomy.get.others:
    description: Allows you to get the balance of someone
    default: op
  vconomy.admin.give:
    description: Allows you to give someone money
    default: op
  vconomy.admin.take:
    description: Allows you to take money from someone
    default: op
  vconomy.admin.set:
    description: Allows you to set the money of someone
    default: op
  vconomy.admin.reset:
    description: Allows you to reset the money of someone
    default: op
  vconomy.reload:
    description: Allows you to reload the plugin
    default: op
  vconomy.admin.help:
    description: Allows you to see the admin help messages
    default: op